AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
         BlockPublicPolicy: false   # By default, assigning bucket policies to the bucket is blocked
  
  MyBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal: '*'
            Action: 's3:*'
            Resource: !Join
            - ''
            - - 'arn:aws:s3:::'
              - !Ref MyS3Bucket
              - /*

